image: node:latest

services:
  - redis:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  image: cypress/base:10
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

unit-test:
  stage: test
  script:
    # check if dependencies are installed and up-to-date
    - npm install
    - npm run ci:unit

e2e-test:
  image: cypress/base:10
  stage: test
  script:
    # check if dependencies are installed and up-to-date
    - npm install
    # install cypress binary to run test
    - npx cypress install
    # start server and run test
    - npm run ci:e2e
  artifacts:
    when: always
    paths:
      - cypress/video/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
