name: Test, build, and deploy to Heroku

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build
        env:
          NODE_ENV: production
          REDIS_URL: ${{secrets.REDIS_URL}}

      - name: Run all tests
        run: |
          npm test
        env:
          NODE_ENV: test
          REDIS_URL: ${{secrets.REDIS_URL}}
